=== raghera/er-common/ER_api/schemas/currencycodes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v5 rel. 4 U (http://www.xmlspy.com) by Ly Le (Vodafone US) -->
<!--W3C Schema generated by XMLSPY v5 rel. 4 U (http://www.xmlspy.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="code" type="xs:int"/>
	<xs:element name="currencies">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="currency" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="currency">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="code"/>
				<xs:element ref="name"/>
				<xs:element ref="symbol" minOccurs="0"/>
				<xs:element ref="description" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="description" type="xs:string"/>
	<xs:element name="name" type="xs:string"/>
	<xs:element name="symbol" type="xs:string"/>
</xs:schema>

=== raghera/er-common/ER_api/src/main/resources/ecom/currencycodes.xml
<?xml version="1.0" encoding="UTF-8"?>
<currencies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Y:\dev\erdev\us\dev\er\working\ER_catalog\resources\currencycodes.xsd">
	<currency>
		<code>840</code>
		<name>USD</name>
		<symbol>$</symbol>
		<description>US Dollar</description>
	</currency>
	<currency>
		<code>036</code>
		<name>AUD</name>
		<symbol>A$</symbol>
		<description>Australian Dollar</description>
	</currency>
	<currency>
		<code>124</code>
		<name>CAD</name>
		<symbol>Can$</symbol>
		<description>Canadian Dollar</description>
	</currency>
	<currency>
		<code>756</code>
		<name>CHF</name>
		<symbol>SFr.</symbol>
		<description>Swiss France</description>
	</currency>
	<currency>
		<code>826</code>
		<name>GBP</name>
		<symbol>L</symbol>
		<description>British Pound Sterling</description>
	</currency>
	<currency>
		<code>392</code>
		<name>JPY</name>
		<symbol>Yen</symbol>
		<description>Japanese Yen</description>
	</currency>
	<currency>
		<code>978</code>
		<name>EUR</name>
		<symbol>E</symbol>
		<description>Euro</description>
	</currency>
	<currency>
		<code>250</code>
		<name>FRF</name>
		<symbol>F</symbol>
		<description>French Franc</description>
	</currency>
	<currency>
		<code>280</code>
		<name>DEM></name>
		<symbol>DM</symbol>
		<description>Deutsche Mark</description>
	</currency>
	<currency>
		<code>380</code>
		<name>ITL</name>
		<symbol>L.</symbol>
		<description>Italian Lira</description>
	</currency>
	<currency>
		<code>528</code>
		<name>NLG</name>
		<symbol>f.</symbol>
		<description>Netherlands Guilder</description>
	</currency>
	<currency>
		<code>56</code>
		<name>BEF</name>
		<symbol>BF</symbol>
		<description>Belgian Franc</description>
	</currency>
	<currency>
		<code>724</code>
		<name>ESP</name>
		<symbol>Pts</symbol>
		<description>Spanish Peseta</description>
	</currency>
	<currency>
		<code>246</code>
		<name>FIM</name>
		<symbol>mk</symbol>
		<description>Finnish Markka</description>
	</currency>
	<currency>
		<code>372</code>
		<name>IEP</name>
		<symbol>IRL</symbol>
		<description>Irish Pound</description>
	</currency>
	<currency>
		<code>40</code>
		<name>ATS</name>
		<symbol>oS</symbol>
		<description>Austrian Schilling</description>
	</currency>
	<currency>
		<code>442</code>
		<name>LUF</name>
		<symbol>LuxF</symbol>
		<description>Luxembourg Franc</description>
	</currency>
	<currency>
		<code>620</code>
		<name>PTE</name>
		<symbol>Esc.</symbol>
		<description>Portugese Escudo</description>
	</currency>
	<currency>
		<code>348</code>
		<name>HUF</name>
		<symbol>HUF</symbol>
		<description>Hungarian Forint</description>
	</currency>
	<currency>
		<code>616</code>
		<name>PLZ</name>
		<symbol>PLZ</symbol>
		<description>Polish Zloty</description>
	</currency>
	<currency>
		<code>642</code>
		<name>ROL</name>
		<symbol>ROL</symbol>
		<description>Romanian Leu</description>
	</currency>
	<currency>
		<code>752</code>
		<name>SEK</name>
		<symbol>SEK</symbol>
		<description>Swedish Krona</description>
	</currency>
	<currency>
		<code>300</code>
		<name>GRD</name>
		<symbol>GRD</symbol>
		<description>Greek Drachma</description>
	</currency>
	<currency>
		<code>554</code>
		<name>NZD</name>
		<symbol>NZD</symbol>
		<description>New Zealand Dollar</description>
	</currency>
	<currency>
		<code>203</code>
		<name>CZK</name>
		<symbol>CZK</symbol>
		<description>Czech Republic Koruny</description>
	</currency>
	<currency>
		<code>352</code>
		<name>ISK</name>
		<symbol>ISK</symbol>
		<description>Iceland Kronur</description>
	</currency>
	<currency>
		<code>792</code>
		<name>TRL</name>
		<symbol>TRL</symbol>
		<description>Turkey Lira</description>
	</currency>
	<currency>
		<code>949</code>
		<name>TL</name>
		<symbol>TL</symbol>
		<description>Turkey Lira</description>
	</currency>
	<currency>
		<code>975</code>
		<name>BGN</name>
		<symbol>BGN</symbol>
		<description>Bulgaria Lev</description>
	</currency>
	<currency>
		<code>941</code>
		<name>RSD</name>
		<symbol>RSD</symbol>
		<description>Serbian Dinar</description>
	</currency>
	<currency>
		<code>807</code>
		<name>MKD</name>
		<symbol>MKD</symbol>
		<description>Macedonian Denar</description>
	</currency>
	<currency>
		<code>356</code>
		<name>INR</name>
		<symbol>INR</symbol>
		<description>Indian Rupee</description>
	</currency>
	<currency>
		<code>643</code>
		<name>RUB</name>
		<symbol>RUB</symbol>
		<description>Russian Ruble</description>
	</currency>
	<currency>
		<code>152</code>
		<name>CLP</name>
		<symbol>CLP</symbol>
		<description>Chilean Peso</description>
	</currency>
	<currency>
		<code>976</code>
		<name>CDF</name>
		<symbol>CDF</symbol>
		<description>Congo Democratic Franc</description>
	</currency>
	<currency>
		<code>834</code>
		<name>TZS</name>
		<symbol>TZS</symbol>
		<description>Tanzanian Shilling</description>
	</currency>
	<currency>
		<code>936</code>
		<name>GHC</name>
		<symbol>GHC</symbol>
		<description>Ghanian Cedi</description>
	</currency>
	<currency>
		<code>634</code>
		<name>QAR</name>
		<symbol>QAR</symbol>
		<description>Qatar Rial</description>
	</currency>
	<currency>
		<code>008</code>
		<name>ALL</name>
		<symbol>ALL</symbol>
		<description>Albanian Lek</description>
	</currency>
	<currency>
		<code>242</code>
		<name>FJD</name>
		<symbol>FJD</symbol>
		<description>Fijian Dollar</description>
	</currency>
	<currency>
		<code>32</code>
		<name>ARS</name>
		<symbol>ARS</symbol>
		<description>Argentinian Peso</description>
	</currency>
	<currency>
		<code>986</code>
		<name>BRL</name>
		<symbol>BRL</symbol>
		<description>Brazilian Real</description>
	</currency>
	<currency>
		<code>170</code>
		<name>COP</name>
		<symbol>COP</symbol>
		<description>Columbian Peso</description>
	</currency>
	<currency>
		<code>214</code>
		<name>DOP</name>
		<symbol>DOP</symbol>
		<description>Dominican Republic Peso</description>
	</currency>
	<currency>
		<code>320</code>
		<name>GTQ</name>
		<symbol>GTQ</symbol>
		<description>Guatemalanian Quetzale</description>
	</currency>
	<currency>
		<code>340</code>
		<name>HNL</name>
		<symbol>HNL</symbol>
		<description>Honduranian Lempira</description>
	</currency>
	<currency>
		<code>484</code>
		<name>MXN</name>
		<symbol>MXN</symbol>
		<description>Mexican Peso</description>
	</currency>
	<currency>
		<code>558</code>
		<name>NIO</name>
		<symbol>NIO</symbol>
		<description>Nicaraguan Cordoba</description>
	</currency>
	<currency>
		<code>600</code>
		<name>PYG</name>
		<symbol>PYG</symbol>
		<description>Paraguain Guarani</description>
	</currency>
	<currency>
		<code>604</code>
		<name>PEN</name>
		<symbol>PEN</symbol>
		<description>Peruvian Nuevo Sol</description>
	</currency>
	<currency>
		<code>858</code>
		<name>UYU</name>
		<symbol>UYU</symbol>
		<description>Uraguain Peso</description>
	</currency>
	<!-- CR1503 - Multi Price plans -->
	<currency>
		<code>999</code>
		<name>XXX</name>
		<symbol>XXX</symbol>
		<description>Global Currency</description>
	</currency>
	<!-- CR1503 - Ends -->
	<!-- MQC 8341 add missing values -->
	<currency>
		<code>191</code>
		<name>HRK</name>
		<symbol>HRK</symbol>
		<description>Croation Kuna</description>
	</currency>
	<currency>
		<code>818</code>
		<name>EGP</name>
		<symbol>EGP</symbol>
		<description>Egyptian Pound</description>
	</currency>
	<currency>
		<code>048</code>
		<name>BHD</name>
		<symbol>BHD</symbol>
		<description>Bahraini Dinar</description>
	</currency>
	<currency>
		<code>208</code>
		<name>DKK</name>
		<symbol>DKK</symbol>
		<description>Danish Krone</description>
	</currency>
	<currency>
		<code>233</code>
		<name>EEK</name>
		<symbol>EEK</symbol>
		<description>Estonian Kroon</description>
	</currency>
	<currency>
		<code>400</code>
		<name>JOD</name>
		<symbol>JOD</symbol>
		<description>Jordanian Dinar</description>
	</currency>
	<currency>
		<code>414</code>
		<name>KWD</name>
		<symbol>KWD</symbol>
		<description>Kuwaiti Dinar</description>
	</currency>
	<currency>
		<code>458</code>
		<name>MYR</name>
		<symbol>MYR</symbol>
		<description>Malaysian Ringgit</description>
	</currency>
	<currency>
		<code>702</code>
		<name>SGD</name>
		<symbol>SGD</symbol>
		<description>Singapore Dollar</description>
	</currency>	
	<currency>
		<code>710</code>
		<name>ZAR</name>
		<symbol>ZAR</symbol>
		<description>Namibia Rand</description>
	</currency>	
</currencies>
